### ISSUE TITLE
Add an api endpoint to receive combined information about and endpoint and endpointInformation 

### ISSUE THREAD

**Issue by melsner11** [christophperrins/poller-vertx-rxjava#4]
Add an api endpoint to receive combined information about and endpoint and endpointInformation. The new API endpoint should combine data from both API endpoints endpoint and endPointInformation.

Steps: 

1. Create model, repository, service, controller for endPointInformation
    basic information : 
class Information:
    (private Long id;)
    (private Long endPointId;)
    private String owner;
    private String street;
    private String postcode;
    private String city;

2. Create controller for API endpoint "endPointMeta"
2.1 Should have a method to receive endpoint and endpointInformation for a given endpointId  
2.1 Should have a method to receive more than one endpoint and endpointInformation for more than one given endpointId's as an array of objects  

Controllers:
EndpointController     (no change)
EndpointHistoryController     (no change)

InformationController     +      
     -> InformationService       +
               -> InformationRepository   +

----------------------------

EndpointMetaDataController   (combines data and meta)
      -> EndpointService    (no change)
      -> InformationService   

Single<?> getInformationByEndpointId(long id)
Single<List<?>> getInformationByEndpointIds(long[] ids)

**Comment by christophperrins** [comment]
This has just become a space for reference. Closing as it has been split into issues #5 and #6
